### ISSUE TITLE
TODOList

### ISSUE THREAD

**Issue by GreGGus** [robinsonroy/WebArena#7]
Ninja ARENA :

TODO List :

-Fighters sur (X,Y), avec un seul fighter par case. Pop random
-Fighter : vue = 0
        force = 1
                pdv = 3
-X : 15 ; Y : 10
-Vue : porté de la vue du personnage
-Force : Attaque du personnage.
-PDV :  Si 0 => delete personnage.
-Attaque peut échouer ou réussir selon algo. ( à voir sur pdf ).
-XP : Chaque attaque succes : 1pt
          Kill : 1pt + lvl du mort.
          Lvl up 4xp => +1 force/+1vue ou +3pdv.
-Chaque evenement est affiché en haut.

En gros, c'est l'algo du jeu.

**Comment by sambres** [comment]
TODO
ne pas afficher les persos morts dans sight (current_health == 0)
ne pas afficher les persos pas dans le champ de vision
